### ISSUE TITLE
Manually Steer and visualise bird's eye view

### ISSUE THREAD

**Issue by Mohith22** [deepsense-ai/carla_birdeye_view#2]
In Carla, there is a file in carla-simulator/PythonAPI/examples/manual_control.py which lets me drive around the town to collect simulation data.  Is it possible to visualize bird's eye view in that setting through this package?

**Comment by Mohith22** [comment]
Figured it.  Thanks!

**Comment by hlsafin** [comment]
what was the solution? I am trying to do the same
